from enum import Enum, auto


class MultiTablePrismaDVTasks(Enum):
    TABLE_COLUMN_ACCESS_DETECTION = auto()
    TABLE_COLUMN_DATA_FLOW_INSPECTION = auto()
    TABLE_COLUMN_ASSUMPTION_GENERATION = auto()
    TABLE_COLUMN_CODE_GENERATION = auto()
    TABLE_COLUMN_GROUP_DISCOVERY = auto()
    TABLE_COLUMN_GROUP_DATA_FLOW_INSPECTION = auto()
    TABLE_COLUMN_GROUP_ASSUMPTION_GENERATION = auto()
    TABLE_COLUMN_GROUP_CODE_GENERATION = auto()
    TABLE_COLUMN_DIRECT_CODE_GENERATION = auto()
    TABLE_COLUMN_GROUP_DIRECT_CODE_GENERATION = auto()
